format_version: 3
pipelines:
  dev-pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/jtanium/mathematically
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          rspec:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install
                command: bundle
                run_if: passed
            - exec:
                arguments:
                - spec
                command: rspec
                run_if: passed
